In [ ]:
'''
【课程2.1】  Pandas数据结构Series：基本概念及创建

"一维数组"Serise

'''

In [2]:
# Series 数据结构
# Series 是带有标签的一组数组，可以保存任何数据类型（整数，字符串，浮点数，python对象等），轴标签统称为索引

import numpy as np
import pandas as pd
# 导入numpy、pandas模块

s = pd.Series(np.random.rand(5))
print(s)
print(type(s))
# 查看数据、数据类型


print(s.index, type(s.index))
print(s.values, type(s.values))
# .index查看series索引，类型为rangeindex
# .values查看series值，类型是ndarray

# 核心：series相当于ndarray，是一个自带索引index的数组 -> 一维数组 + 对应索引
# 所以当只看series的值的时候，就是一个ndarray
# series和ndarray较相似，索引切片功能差别不大
# series和dict相比，series更像一个有顺序的字典（dict本身不存在顺序），其索引原理与字典相似（一个用key，一个用index)


0    0.139659
1    0.296819
2    0.305464
3    0.177713
4    0.241560
dtype: float64
<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=5, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
[ 0.13965911  0.29681901  0.30546434  0.17771312  0.24155965] <class 'numpy.ndarray'>


In [22]:
# Series 创建方法一：由字典创建，字典的key就是index，values就是values

dic = {"a": 1, "b": 2, "c": 3, "4": 4, "5":5}
s = pd.Series(dic)
print(s)
dic = {'a':1 ,'b':'hello' , 'c':3, '4':4, '5':5}
# 注意：key肯定是字符串，假如values类型不止一个会怎么样？-> dic = {'a':1 ,'b':'hello' , 'c':3, '4':4, '5':5}

4    4
5    5
a    1
b    2
c    3
dtype: int64


In [25]:
# Series 创建方法二：由数组创建（一维数组）

arr = np.random.randn(5)
s = pd.Series(arr)
print(arr)
print(s)
# 默认index是从0开始，步长为1的数字

s = pd.Series(arr, index = ["a", "b", "c", "d", "e"], dtype = np.object)
print(s)
# index参数：设置index，长度保持一致
# dtype参数：设置数值类型

[-1.02694698  0.87887104  0.32315567  2.22775189  0.5681097 ]
0   -1.026947
1    0.878871
2    0.323156
3    2.227752
4    0.568110
dtype: float64
a    -1.02695
b    0.878871
c    0.323156
d     2.22775
e     0.56811
dtype: object


In [26]:
# Series 创建方法三：由标量创建

s = pd.Series(10, index = range(4))
print(s)
# 如果data是标量值，则必须提供索引。该值会重复，来匹配索引的长度

0    10
1    10
2    10
3    10
dtype: int64


In [32]:
# Series 名称属性：name

s1 = pd.Series(np.random.randn(5))
print(s1)
print("---------")
s2 = pd.Series(np.random.randn(5), name = "test")
print(s2)
print(s1.name, s2.name, type(s2.name))
print("---------")
# name为Series的一个参数，创建一个数组的名称
# .name方法：输出数组的名称，输出格式为str，如果没用定义输出名称，输出为None

s3 = s2.rename("hehehe")
print(s3)
print(s3.name, s2.name)
# .rename()重命名一个数组的名称，并且新指向一个数组，原数组不变

0    0.921083
1    0.221778
2   -0.898440
3   -1.328778
4    1.106824
dtype: float64
---------
0    0.234609
1   -1.024634
2   -0.738751
3    2.016070
4    2.274898
Name: test, dtype: float64
None test <class 'str'>
---------
0    0.234609
1   -1.024634
2   -0.738751
3    2.016070
4    2.274898
Name: hehehe, dtype: float64
hehehe test


In [ ]:
'''
【课程2.2】  Pandas数据结构Series：索引

位置下标 / 标签索引 / 切片索引 / 布尔型索引

'''

In [16]:
# 位置下标，类似序列

s = pd.Series(np.random.rand(5))
print(s)
print(s[0], type(s[0]), s[0].dtype)
print(float(s[0]), type(float(s[0])))
# print(s[-1])
# 位置下标从0开始
# 输出结果为numpy.float格式
# 可以通过float()函数转换为python float 格式
# numpy.float与float占用字节不同 
# s[-1]结果如何？

0    0.560968
1    0.493516
2    0.062140
3    0.312413
4    0.904077
dtype: float64
0.560967922803 <class 'numpy.float64'> float64
0.5609679228028187 <class 'float'>


In [22]:
# 标签索引

s = pd.Series(np.random.rand(5), index = ["a", "b", "c", "d", "e"])
print(s)
print(s["a"], type(s["a"]), s["a"].dtype)
# 方法类似下标索引，用[]表示，内写上index，注意index是字符串

sci = s[["a", "b", "e"]]
print(sci, type(sci))
# 如果需要选择多个标签的值，用[[]]来表示（相当于[]中包含一个列表）
# 多标签索引结果是新的数组

a    0.213776
b    0.182475
c    0.099063
d    0.048114
e    0.347225
dtype: float64
0.213776129301 <class 'numpy.float64'> float64
a    0.213776
b    0.182475
e    0.347225
dtype: float64 <class 'pandas.core.series.Series'>


In [27]:
# 切片索引

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5), index = ["a", "b", "c", "d", "e"])
print(s1[1:4], s1[4])
print(s2["a":"c"], s2["c"])
print(s2[0:3], s2[3])
print("-------------")
# 注意：用index做切片是末端包含

print(s2[:-1])
print(s2[::2])
# 下标索引做切片，和list写法一样

1    0.111338
2    0.028638
3    0.646714
dtype: float64 0.358315313479
a    0.691003
b    0.334908
c    0.383004
dtype: float64 0.383004452952
a    0.691003
b    0.334908
c    0.383004
dtype: float64 0.455667154779
-------------
a    0.691003
b    0.334908
c    0.383004
d    0.455667
dtype: float64
a    0.691003
c    0.383004
e    0.767322
dtype: float64


In [35]:
# 布尔型索引

s = pd.Series(np.random.rand(3)*100)
s[4] = None # 添加一个空值
print(s)
bs1 = s > 50
bs2 = s.isnull()
bs3 = s.notnull()
print(bs1, type(bs1), bs1.dtype)
print(bs2, type(bs2), bs2.dtype)
print(bs3, type(bs3), bs2.dtype)
print("-------------")
# 数组做判断之后，返回的是一个由布尔值组成的新的数组
# .isnull() / .notnull() 判断是否为空值 (None代表空值，NaN代表有问题的数值，两个都会识别为空值)

print(s[s > 50])
print(s[bs3])
# 布尔型索引方法：用[判断条件]表示，其中判断条件可以是 一个语句，或者是 一个布尔型数组！

0    96.5709
1    72.6577
2      12.75
4       None
dtype: object
0     True
1     True
2    False
4    False
dtype: bool <class 'pandas.core.series.Series'> bool
0    False
1    False
2    False
4     True
dtype: bool <class 'pandas.core.series.Series'> bool
0     True
1     True
2     True
4    False
dtype: bool <class 'pandas.core.series.Series'> bool
-------------
0    96.5709
1    72.6577
dtype: object
0    96.5709
1    72.6577
2      12.75
dtype: object


In [ ]:
'''
【课程2.3】  Pandas数据结构Series：基本技巧

数据查看 / 重新索引 / 对齐 / 添加、修改、删除值

'''

In [38]:
# 数据查看

s = pd.Series(np.random.rand(50))
print(s.head(10))
print(s.tail())
# .head()查看头部数据
# .tail()查看尾部数据
# 默认查看5条

0    0.277002
1    0.317063
2    0.811060
3    0.765574
4    0.593932
5    0.739993
6    0.086348
7    0.982307
8    0.364677
9    0.258351
dtype: float64
45    0.743516
46    0.411566
47    0.851413
48    0.848713
49    0.212264
dtype: float64


In [42]:
# 重新索引reindex
# .reindex将会根据索引重新排序，如果当前索引不存在，则引入缺失值

s = pd.Series(np.random.rand(3), index = ['a','b','c'])
print(s)
s1 = s.reindex(['a','b','c', "d"])
print(s1)
# .reindex()中也是写列表
# 这里"d"索引不存在，所以值为NaN

s2 = s.reindex(list("cbad"), fill_value = 0)
print(s2)
# fill_value参数：填充缺失值的值

a    0.572551
b    0.509950
c    0.850255
dtype: float64
a    0.572551
b    0.509950
c    0.850255
d         NaN
dtype: float64
c    0.850255
b    0.509950
a    0.572551
d    0.000000
dtype: float64


In [48]:
# Series对齐

s1 = pd.Series(np.random.rand(3), index = ['Jack','Marry','Tom'])
s2 = pd.Series(np.random.rand(3), index = ['Wang','Jack','Marry'])
print(s1)
print(s2)
print(s1 + s2)
# Series 和 ndarray之间的主要区别是： Series上的操作会根据标签自动对齐
# index顺序不会影响数值计算，以标签来计算
# 空值和任何值计算结果仍为空值
# PS:上面的结果是相同的index就会相加，比如s1["Jack"] + s2["Jack"]是这个意思

Jack     0.196502
Marry    0.539981
Tom      0.113609
dtype: float64
Wang     0.944202
Jack     0.743035
Marry    0.659737
dtype: float64
Jack     0.939537
Marry    1.199718
Tom           NaN
Wang          NaN
dtype: float64


In [51]:
# 删除：.drop

s = pd.Series(np.random.rand(5), index = list("ngjur"))
print(s)
s1 = s.drop("n")
s2 = s.drop(["g", "j"])
print(s1)
print(s2)
print(s)
# drop删除元素之后返回副本（inplace = False）

n    0.236251
g    0.431352
j    0.786431
u    0.214351
r    0.807724
dtype: float64
g    0.431352
j    0.786431
u    0.214351
r    0.807724
dtype: float64
n    0.236251
u    0.214351
r    0.807724
dtype: float64
n    0.236251
g    0.431352
j    0.786431
u    0.214351
r    0.807724
dtype: float64


In [56]:
# 添加

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5), index = list("ngjur"))
print(s1)
print(s2)
s1[5] = 100
s2["a"] = 200
print(s1)
print(s2)
print("---------")
# 直接通过下标索引/标签index添加值

s3 = s1.append(s2)
print(s3)
# 通过.append方法，直接添加一个数组
# .append方法生成一个新的数组，不改变之前的数组

0    0.969831
1    0.782475
2    0.775078
3    0.178143
4    0.058379
dtype: float64
n    0.507924
g    0.192238
j    0.401397
u    0.513251
r    0.871474
dtype: float64
0      0.969831
1      0.782475
2      0.775078
3      0.178143
4      0.058379
5    100.000000
dtype: float64
n      0.507924
g      0.192238
j      0.401397
u      0.513251
r      0.871474
a    200.000000
dtype: float64
---------
0      0.969831
1      0.782475
2      0.775078
3      0.178143
4      0.058379
5    100.000000
n      0.507924
g      0.192238
j      0.401397
u      0.513251
r      0.871474
a    200.000000
dtype: float64


In [59]:
# 修改

s = pd.Series(np.random.rand(3), index = list("abc"))
print(s)
s["a"] = 100
s[["b", "c"]] = 200
print(s)
# 通过索引直接修改，类似序列

a    0.406925
b    0.024699
c    0.284828
dtype: float64
a    100.0
b    200.0
c    200.0
dtype: float64


In [ ]:
'''
【课程2.4】  Pandas数据结构Dataframe：基本概念及创建

"二维数组"Dataframe：是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。

Dataframe中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。

'''


In [12]:
# Dataframe 数据结构
# Dataframe是一个表格型的数据结构，“带有标签的二维数组”。
# Dataframe带有index（行标签）和columns（列标签）

data = {"name": ['Jack','Tom','Mary'], 
        "age": [18,19,20],
        "gender": ["m","m","w"]
       }
frame = pd.DataFrame(data)
print(frame)
print(type(frame))
print(frame.index,"\n该数据类型为：",type(frame.index))
print(frame.columns,'\n该数据类型为：',type(frame.columns))
print(frame.values,'\n该数据类型为：',type(frame.values))
# 查看数据，数据类型为dataframe
# .index查看行标签
# .columns查看列标签
# .values查看值，数据类型为ndarray

   age gender  name
0   18      m  Jack
1   19      m   Tom
2   20      w  Mary
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 
该数据类型为： <class 'pandas.core.indexes.range.RangeIndex'>
Index(['age', 'gender', 'name'], dtype='object') 
该数据类型为： <class 'pandas.core.indexes.base.Index'>
[[18 'm' 'Jack']
 [19 'm' 'Tom']
 [20 'w' 'Mary']] 
该数据类型为： <class 'numpy.ndarray'>


In [24]:
# Dataframe 创建方法一：由数组/list组成的字典
# 创建方法:pandas.Dataframe()

data1 = {"a": [1,2,3],
         "b": [3,4,5],
         "c": [5,6,7]
        }
data2 = {"one": np.random.rand(3),
         "two": np.random.rand(3) # 这里如果尝试  'two':np.random.rand(4) 会怎么样？
        }
print(data1)
print(data2)

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
# 由数组/list组成的字典 创建Dataframe，columns为字典key，index为默认数字标签
# 字典的值的长度必须保持一致！

df1 = pd.DataFrame(data1, columns = ['b','c','a','d'])
print(df1)
df1 = pd.DataFrame(data1, columns = ['b','c'])
print(df1)
# columns参数：可以重新指定列的顺序，格式为list，如果现有数据中没有该列（比如'd'），则产生NaN值
# 如果columns重新指定时候，列的数量可以少于原数据

df2 = pd.DataFrame(data2, index = ['f1','f2','f3'])  # 这里如果尝试  index = ['f1','f2','f3','f4'] 会怎么样？
print(df2)
# index参数：重新定义index，格式为list，长度必须保持一致

{'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6, 7]}
{'one': array([ 0.70824335,  0.84011347,  0.6113807 ]), 'two': array([ 0.70723487,  0.12187474,  0.84577133])}
   a  b  c
0  1  3  5
1  2  4  6
2  3  5  7
        one       two
0  0.708243  0.707235
1  0.840113  0.121875
2  0.611381  0.845771
   b  c  a    d
0  3  5  1  NaN
1  4  6  2  NaN
2  5  7  3  NaN
   b  c
0  3  5
1  4  6
2  5  7
         one       two
f1  0.708243  0.707235
f2  0.840113  0.121875
f3  0.611381  0.845771


In [27]:
# DataFrame 创建方法二：由Series组成的字典

data1 = {"one": pd.Series(np.random.rand(2)),
         "two": pd.Series(np.random.rand(3)) # 没有设置index的Series
        }
data2 = {"one": pd.Series(np.random.rand(2), index = ["a", "b"]),
         "two": pd.Series(np.random.rand(3), index = ["a", "b", "c"])  # 设置了index的Series
        }
print(data1)
print(data2)
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
# 由Seris组成的字典 创建Dataframe，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）
# Series可以长度不一样，生成的Dataframe会出现NaN值

{'one': 0    0.256007
1    0.937857
dtype: float64, 'two': 0    0.390475
1    0.548695
2    0.853570
dtype: float64}
{'one': a    0.111607
b    0.344046
dtype: float64, 'two': a    0.405647
b    0.998031
c    0.019877
dtype: float64}
        one       two
0  0.256007  0.390475
1  0.937857  0.548695
2       NaN  0.853570
        one       two
a  0.111607  0.405647
b  0.344046  0.998031
c       NaN  0.019877


In [31]:
# DataFrame 创建方法三：通过二维数组直接创建

ar = np.random.rand(9).reshape(3,3)
print(ar)
df1 = pd.DataFrame(ar)
df2 = pd.DataFrame(ar, index = ['a', 'b', 'c'], columns = ['one','two','three']) # 可以尝试一下index或columns长度不等于已有数组的情况
print(df1)
print(df2)
# 通过二维数组直接创建Dataframe，得到一样形状的结果数据，如果不指定index和columns，两者均返回默认数字格式
# index和colunms指定长度与原数组保持一致

[[ 0.04827809  0.18889651  0.64144429]
 [ 0.98297813  0.96843902  0.19228992]
 [ 0.70065193  0.83740653  0.28605327]]
          0         1         2
0  0.048278  0.188897  0.641444
1  0.982978  0.968439  0.192290
2  0.700652  0.837407  0.286053
        one       two     three
a  0.048278  0.188897  0.641444
b  0.982978  0.968439  0.192290
c  0.700652  0.837407  0.286053


In [33]:
# Dataframe 创建方法四：由字典组成的列表

data = [{"one": 1, "two": 2}, {'one': 5, 'two': 10, 'three': 20}]
print(data)
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index = ["a", "b"])
df3 = pd.DataFrame(data, columns = ["one", "two"])
print(df1)
print(df2)
print(df3)

[{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
   one  three  two
0    1    NaN    2
1    5   20.0   10
   one  three  two
a    1    NaN    2
b    5   20.0   10
   one  two
0    1    2
1    5   10


In [35]:
# Dataframe 创建方法五：由字典组成的字典

data = {'Jack':{'math':90,'english':89,'art':78},
       'Marry':{'math':82,'english':95,'art':92},
       'Tom':{'math':78,'english':67}}
df1 = pd.DataFrame(data)
print(df1)
# 由字典组成的字典创建Dataframe，columns为字典的key，index为子字典的key

df2 = pd.DataFrame(data, columns = ['Jack','Tom','Bob'])
df3 = pd.DataFrame(data, index = ['a','b','c'])
print(df2)
print(df3)
# columns参数可以增加和减少现有列，如出现新的列，值为NaN
# index在这里和之前不同，并不能改变原有index，如果指向新的标签，值为NaN （非常重要！）

         Jack  Marry   Tom
art        78     92   NaN
english    89     95  67.0
math       90     82  78.0
         Jack   Tom  Bob
art        78   NaN  NaN
english    89  67.0  NaN
math       90  78.0  NaN
   Jack  Marry  Tom
a   NaN    NaN  NaN
b   NaN    NaN  NaN
c   NaN    NaN  NaN


In [ ]:
'''
【课程2.5】  Pandas数据结构Dataframe：索引

Dataframe既有行索引也有列索引，可以被看做由Series组成的字典（共用一个索引）

选择列 / 选择行 / 切片 / 布尔判断

'''

In [9]:
# 选择行与列
ar = np.random.rand(12).reshape(3,4)*100
print(ar)
df = pd.DataFrame(ar,
                 index = ["one", "two", "three"],
                  columns = ["a", "b", "c", "d"])
print(df)

data1 = df["a"]
data2 = df[["a", "c"]]
print(data1, type(data1))
print(data2, type(data2))
print("-----------")
# 按照列名选择列，只选择一列输出Series，选择多列输出DataFrame

data3 = df.loc["one"]
data4 = df.loc[["one", "two"]]
print(data3, type(data3))
print(data4, type(data4))
# 按照index选择行，只选择一行输出Series，选择多行输出DataFrame

[[ 63.50353304   6.22276106  21.06900955  76.67003853]
 [ 59.16521657   3.98573124  37.33884169  57.30312365]
 [ 30.90508412  17.15797723  39.66060664  15.32482961]]
               a          b          c          d
one    63.503533   6.222761  21.069010  76.670039
two    59.165217   3.985731  37.338842  57.303124
three  30.905084  17.157977  39.660607  15.324830
one      63.503533
two      59.165217
three    30.905084
Name: a, dtype: float64 <class 'pandas.core.series.Series'>
               a          c
one    63.503533  21.069010
two    59.165217  37.338842
three  30.905084  39.660607 <class 'pandas.core.frame.DataFrame'>
-----------
a    63.503533
b     6.222761
c    21.069010
d    76.670039
Name: one, dtype: float64 <class 'pandas.core.series.Series'>
             a         b          c          d
one  63.503533  6.222761  21.069010  76.670039
two  59.165217  3.985731  37.338842  57.303124 <class 'pandas.core.frame.DataFrame'>


In [17]:
# df[] - 选择列
# 一般用于选择列，也可以选择行
ar = np.random.rand(12).reshape(3,4)*100
df = pd.DataFrame(ar, index = ["one", "two", "three"],
                 columns = ["a", "b", "c", "d"])
print(df)
print("-----------")

data1 = df["a"]
data2 = df[["b", "c"]] # 尝试输入 data2 = df[["b", "c", "e"]]
print(data1)
print(data2)
# df[]默认选择列，[]中写列名（所以一般数据colunms都会单独制定，不会用默认数字列名，以免和index冲突）
# 单选列为Series，print结果为Series格式
# 多选列为Dataframe，print结果为Dataframe格式

data3 = df[:1]
# data3 = df[0]
# data3 = df["one"]
print(data3, type(data3))
# df[]中为数字时，默认选择行，且只能进行切片的选择，不能单独选择（df[0]）
# 输出结果为DataFrame，即便只选择一行
# df[]不能通过索引标签名来选择行(df["one"])

# 核心笔记：df[col]一般用于选择列，[]中写列名

               a          b          c          d
one    76.026925  89.789335  58.415334   6.344813
two    26.291941  33.279379  37.060433   8.470353
three  15.717342   7.927987  20.894725  76.144591
-----------
one      76.026925
two      26.291941
three    15.717342
Name: a, dtype: float64
               b          c
one    89.789335  58.415334
two    33.279379  37.060433
three   7.927987  20.894725
             a          b          c         d
one  76.026925  89.789335  58.415334  6.344813 <class 'pandas.core.frame.DataFrame'>


In [26]:
# df.loc[] - 按index选择行

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
df2 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df1)
print(df2)
print("--------------")

data1 = df1.loc["one"]
data2 = df2.loc[1]
print(data1)
print(data2)
print('单标签索引\n-----')
# 单个标签索引，返回Series

data3 = df1.loc[["two", "three", "five"]]
data4 = df2.loc[[3,2,1]]
print(data3)
print(data4)
print('多标签索引\n-----')
# 多个标签索引，如果标签不存在，则返回NaN
# 顺序可变

data5 = df1.loc["one":"three"]
data6 = df2.loc[1:3]
print(data5)
print(data6)
print("切片索引")
# 可以做切片对象
# 末端 包含

# 核心笔记：df.loc[label]主要针对index选择行，同时支持指定index，及默认数字index

               a          b          c          d
one    52.465113  86.281971  25.259648  92.348702
two    21.347353  56.761597  85.332899   2.086910
three  63.373646  70.323855  93.542567  35.891443
four   19.261374  90.798023  51.888678  98.924609
           a          b          c          d
0  19.836684  24.861981  56.724701  34.278317
1  54.478773  25.102152  66.756217  37.069234
2  94.054666  68.340560   0.140962  81.306833
3  75.141880  62.802344  15.074228  19.534709
--------------
a    52.465113
b    86.281971
c    25.259648
d    92.348702
Name: one, dtype: float64
a    54.478773
b    25.102152
c    66.756217
d    37.069234
Name: 1, dtype: float64
单标签索引
-----
               a          b          c          d
two    21.347353  56.761597  85.332899   2.086910
three  63.373646  70.323855  93.542567  35.891443
five         NaN        NaN        NaN        NaN
           a          b          c          d
3  75.141880  62.802344  15.074228  19.534709
2  94.054666  68.340560   0.140

In [38]:
# df.iloc[] - 按照整数位置（从轴的0到length-1）选择行
# 类似list的索引，其顺序就是dataFrame的整数位置，从0开始计

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print("----------")


print(df.iloc[0])
print(df.iloc[-1])
# print(df.iloc[4])
print('单位置索引\n-----')
# 单位置索引
# 和loc索引不同，不能索引超出数据行数的整数位置

print(df.iloc[[0,2]])
print(df.iloc[[3,2,1]])
print('多位置索引\n-----')
# 多位置索引
# 顺序可变

print(df.iloc[1:3])
print(df.iloc[::2])
print("切片索引")
# 切片索引
# 末端不包含

               a          b          c          d
one    99.100526  64.968520   6.794771  10.798195
two    46.475771  29.261976   6.635119  79.770463
three  94.393053  64.560589  46.401562  75.801925
four   17.245993   1.866107  14.171236  64.873416
----------
a    99.100526
b    64.968520
c     6.794771
d    10.798195
Name: one, dtype: float64
a    17.245993
b     1.866107
c    14.171236
d    64.873416
Name: four, dtype: float64
单位置索引
-----
               a          b          c          d
one    99.100526  64.968520   6.794771  10.798195
three  94.393053  64.560589  46.401562  75.801925
               a          b          c          d
four   17.245993   1.866107  14.171236  64.873416
three  94.393053  64.560589  46.401562  75.801925
two    46.475771  29.261976   6.635119  79.770463
多位置索引
-----
               a          b          c          d
two    46.475771  29.261976   6.635119  79.770463
three  94.393053  64.560589  46.401562  75.801925
               a          b          c    

In [52]:
# 布尔型索引
# 和Series原理相同

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

b1 = df < 20
print(b1, type(b1))
print(df[b1]) # 也可以书写为 df[df < 20]
print("----------")
# 不做索引则会对数据每个值进行判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

b2 = df["a"] > 50
print(b2, type(b2))
print(df[b2])  # 也可以书写为 df[df['a'] > 50]
print('------')
# 单列做判断
# 索引结果保留 单列判断为True的行数据，包括其他列

b3 = df[["a", "b"]] > 50
print(b3, type(b3))
# print(df[b3]) # 也可以书写为 df[df[['a','b']] > 50]
print('------')
# 多列做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

b4 = df.loc[["one", "three"]] < 50
print(b4, type(b4))
print(df[b4]) # 也可以书写为 df[df.loc[['one','three']] < 50]
print("----------")
# 多行做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

               a          b          c          d
one    91.733340  54.040234  24.693274  28.233348
two    89.955183  54.343341  77.085158  63.693347
three  99.512167  85.536543  70.578933  32.771113
four   30.256432  50.062694  18.444229  29.335684
------
           a      b      c      d
one    False  False  False  False
two    False  False  False  False
three  False  False  False  False
four   False  False   True  False <class 'pandas.core.frame.DataFrame'>
        a   b          c   d
one   NaN NaN        NaN NaN
two   NaN NaN        NaN NaN
three NaN NaN        NaN NaN
four  NaN NaN  18.444229 NaN
----------
one       True
two       True
three     True
four     False
Name: a, dtype: bool <class 'pandas.core.series.Series'>
               a          b          c          d
one    91.733340  54.040234  24.693274  28.233348
two    89.955183  54.343341  77.085158  63.693347
three  99.512167  85.536543  70.578933  32.771113
------
           a     b
one     True  True
two     True  Tru

In [55]:
# 多重索引：比如同时索引行和列
# 先选择列再选择行   --- 相当于对于一个数据，先筛选字段，再选择数据量

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

print(df["a"].loc[["one", "three"]]) # 选择a列的one，three行
print(df[["b", "c", "d"]].iloc[::2]) # 选择b，c，d列的one，three行
print(df[df["a"] < 50].iloc[:2]) # 选择满足判断索引的前两行数据

               a          b          c          d
one    41.424261  93.858188  31.989822  29.382966
two    89.571862  25.789673  99.381680  67.309498
three  60.077175  46.625050  47.212075   6.884013
four   60.397913  91.795944  81.855745  31.558650
------
one      41.424261
three    60.077175
Name: a, dtype: float64
               b          c          d
one    93.858188  31.989822  29.382966
three  46.625050  47.212075   6.884013
             a          b          c          d
one  41.424261  93.858188  31.989822  29.382966


In [ ]:
'''
【课程2.6】  Pandas数据结构Dataframe：基本技巧

数据查看、转置 / 添加、修改、删除值 / 对齐 / 排序

'''

In [18]:
# 数据查看、转置

df = pd.DataFrame(np.random.rand(16).reshape(8,2)*100, columns = ["a", "b"])
print(df.head(2))
print(df.tail())
# .head()查看头部数据
# .tail()查看尾部数据
# 默认查看5条

print(df.T)
# .T 转置

           a          b
0  62.377504  87.628347
1  13.885229  92.266579
           a          b
3  22.225305  17.702451
4  76.957918  17.976424
5  23.932890   2.302789
6  24.099962   8.003267
7  66.616008  15.914400
           0          1          2          3          4          5  \
a  62.377504  13.885229  80.096808  22.225305  76.957918  23.932890   
b  87.628347  92.266579  60.449833  17.702451  17.976424   2.302789   

           6          7  
a  24.099962  66.616008  
b   8.003267  15.914400  


In [23]:
# 添加与修改

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                 columns = ["a", "b", "c", "d"])
print(df)

df["e"] = 10
df.loc[4] = 20
print(df)
# 新增列/行并赋值

df["e"] = 20
df[["a", "c"]] = 100
print(df)
# 索引后直接修改值

           a          b          c          d
0  24.191786  45.934138  27.511341  79.855902
1  19.127799  85.099684  22.420304  56.233190
2  12.294581  25.676586  58.626029  63.315542
3  15.635006  46.212661  53.963457  51.675384
           a          b          c          d   e
0  24.191786  45.934138  27.511341  79.855902  10
1  19.127799  85.099684  22.420304  56.233190  10
2  12.294581  25.676586  58.626029  63.315542  10
3  15.635006  46.212661  53.963457  51.675384  10
4  20.000000  20.000000  20.000000  20.000000  20
     a          b    c          d   e
0  100  45.934138  100  79.855902  20
1  100  85.099684  100  56.233190  20
2  100  25.676586  100  63.315542  20
3  100  46.212661  100  51.675384  20
4  100  20.000000  100  20.000000  20


In [31]:
# 删除 del / drop()

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                 columns = ["a", "b", "c", "d"])
print(df)

del df["a"]
print(df)
print("---------")
# del语句 - 删除列

print(df.drop(0))
print(df.drop([1,2]))
print(df)
# drop()删除行，inplace=False -> 删除后生成新的数据，不改变原数据

print(df.drop(["d"], axis = 1))
print(df)
# drop()删除列，需要加上axis = 1, inplace = False -> 删除后生成新的数据，不改变原数据

           a          b          c          d
0  90.548792  13.242182   9.802476  62.061006
1  72.655275  27.851798   1.766409   1.909322
2  48.049667  45.855896  35.341821  67.567391
3  17.131746  11.352275  19.333377  63.982112
           b          c          d
0  13.242182   9.802476  62.061006
1  27.851798   1.766409   1.909322
2  45.855896  35.341821  67.567391
3  11.352275  19.333377  63.982112
---------
           b          c          d
1  27.851798   1.766409   1.909322
2  45.855896  35.341821  67.567391
3  11.352275  19.333377  63.982112
           b          c          d
0  13.242182   9.802476  62.061006
3  11.352275  19.333377  63.982112
           b          c          d
0  13.242182   9.802476  62.061006
1  27.851798   1.766409   1.909322
2  45.855896  35.341821  67.567391
3  11.352275  19.333377  63.982112
           b          c
0  13.242182   9.802476
1  27.851798   1.766409
2  45.855896  35.341821
3  11.352275  19.333377


In [34]:
# 对齐

df1 = pd.DataFrame(np.random.randn(10,4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(7,3), columns=['A', 'B', 'C'])
print(df1 + df2)
# DataFrame对象之间的数据自动按照列和索引（行标签）对齐

          A         B         C   D
0  3.915541 -1.262086  0.320513 NaN
1  0.890254 -1.271860  0.473582 NaN
2 -0.693966  0.696811  0.310805 NaN
3  0.132194 -1.473019 -0.676593 NaN
4  0.735912  2.224669 -1.434812 NaN
5  1.373465 -1.727878  1.267626 NaN
6  0.769009 -1.848404  0.725308 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN


In [43]:
# 排序1 - 按值排序 .sort_values
# 同样适用于Series

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  columns = ["a", "b", "c", "d"])
print(df1)
print(df1.sort_values(["a"], ascending = True)) # 升序
print(df1.sort_values(["a"], ascending = False)) # 升序
print("-------------")
# ascending参数：设置升序降序，默认升序
# 单列排序

df2 = pd.DataFrame({"a": [1,1,1,1,2,2,2,2],
                   "b": list(range(8)),
                   "c": list(range(8,0,-1))})
print(df2)
print(df2.sort_values(["a", "c"]))
# 多列排序，按列顺序排序

           a          b          c          d
0  73.584927  63.387526   3.903934  81.727852
1  38.454921  82.588278  92.843261  82.433146
2  36.123836  63.555703  69.534022  27.465734
3  52.886570  12.261071  94.666279  94.465140
           a          b          c          d
2  36.123836  63.555703  69.534022  27.465734
1  38.454921  82.588278  92.843261  82.433146
3  52.886570  12.261071  94.666279  94.465140
0  73.584927  63.387526   3.903934  81.727852
           a          b          c          d
0  73.584927  63.387526   3.903934  81.727852
3  52.886570  12.261071  94.666279  94.465140
1  38.454921  82.588278  92.843261  82.433146
2  36.123836  63.555703  69.534022  27.465734
-------------
   a  b  c
0  1  0  8
1  1  1  7
2  1  2  6
3  1  3  5
4  2  4  4
5  2  5  3
6  2  6  2
7  2  7  1
   a  b  c
3  1  3  5
2  1  2  6
1  1  1  7
0  1  0  8
7  2  7  1
6  2  6  2
5  2  5  3
4  2  4  4


In [49]:
# 排序2 - 索引排序 .sort_index

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  index = [5, 4, 3, 2],
                  columns = ["a", "b", "c", "d"])
df2 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  index = ["h", "s", "x", "g"],
                  columns = ["a", "b", "c", "d"])
print(df1)
print(df1.sort_index())
print(df2)
print(df2.sort_index())
# 按照index排序
# 默认 ascending=True, inplace=False

           a          b          c          d
5  27.721853   0.055001  78.427025  49.416884
4  83.323310  25.209890   3.939345   0.169508
3  90.523563  63.864451  85.613526  23.736381
2  54.921548  69.258255  15.049575  69.261724
           a          b          c          d
2  54.921548  69.258255  15.049575  69.261724
3  90.523563  63.864451  85.613526  23.736381
4  83.323310  25.209890   3.939345   0.169508
5  27.721853   0.055001  78.427025  49.416884
           a          b          c          d
h  51.854743   3.744013  18.194838  57.188342
s  81.262353   8.064182  34.565437  81.076064
x  63.246686  97.024770   7.310008  43.585541
g  93.173418  96.763088  84.332792  17.839052
           a          b          c          d
g  93.173418  96.763088  84.332792  17.839052
h  51.854743   3.744013  18.194838  57.188342
s  81.262353   8.064182  34.565437  81.076064
x  63.246686  97.024770   7.310008  43.585541
